opt_out_usage
default_platform(:ios)

platform :ios do
    desc "Build for testing"
    lane :build do
        scan(
            scheme: "BLTNBoard",
            build_for_testing: true,
            devices: ["iPhone 7"],
            code_coverage: true,
            derived_data_path: "DerivedData",
            buildlog_path: "build",
            output_directory: "build",
            output_types: "junit"
        )
    end

    desc "Test without building"
    lane :test do
        scan(
            scheme: "BLTNBoard",
            test_without_building: true,
            devices: ["iPhone 7"],
            code_coverage: true,
            derived_data_path: "DerivedData",
            buildlog_path: "test",
            output_directory: "test",
            output_types: "junit"
        )
    end
end
